version: "3"

services:
  chirpstack-network-serverlorawan:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresqllorawan
      - mosquittolorawan
    networks:
      lorawan:
        aliases:
          - chirpstack-network-server

  chirpstack-application-serverlorawan:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-serverlorawan
    networks:
      lorawan:
        aliases:
          - chirpstack-application-server

  chirpstack-gateway-bridgelorawan:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquittolorawan
    networks:
      lorawan:
        ipv4_address: 10.100.120.10

  postgresqllorawan:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ../../samples/chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./volumes/postgresqldatalorawan:/var/lib/postgresql/data
    networks:
      lorawan:
        aliases:
          - postgresql

  redislorawan:
    image: redis:5-alpine
    volumes:
      - ./volumes/redisdatalorawan:/data
    networks:
      lorawan:
        aliases:
          - redis

  mosquittolorawan:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ../../samples/chirpstack/configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      lorawan:
        aliases:
          - mosquitto

volumes:
  postgresqldatalorawan:
  redisdatalorawan:

networks:
  lorawan:
    ipam:
      driver: default
      config:
        - subnet: 10.100.120.0/24
