version: '3'

services:
  my5gcore-ue:
    container_name: non3gpp1-scenary01
    build:
      context: ../../containers/nf_ue
      args:
        DEBUG_TOOLS: "true"
    volumes:
      - ../../samples/iotsgdw/config/ipsec:/my5gcore/ipsec
      - ../../samples/iotsgdw/config/debug.sh:/my5gcore/debug.sh
      - ../../samples/iotsgdw/config:/my5gcore/config
      - ../../bin/runner.sh:/my5gcore/init.sh
      - ./volumes/metrics:/metrics
    environment:
      GIN_MODE: release
      NETSERVER: 10.100.120.10
      NUMDEV: ${DEVS_NUMBERS}
      PACKET: 1000
    extra_hosts:
      - "non3gpp1:192.168.127.2"
      - "n3iwf:192.168.127.1"
    networks:
     scenary1_lorawan:
       aliases:
         - non3gpp1.my5Gcore.org
    cap_add:
      - ALL
    command: sh -c "./debug.sh && ./init.sh nonUE && ./bin/ue "
    #command: sh -c "while true; do echo 'Hit CTRL+C'; sleep 1; done"

volumes:
  metrics:

networks:
  scenary1_lorawan:
     external: true
