version: "3"

services:
  chirpstack-network-serverlorawan2:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresqllorawan2
      - mosquittolorawan2
    networks:
      lorawan2:
        aliases:
           - chirpstack-network-server

  chirpstack-application-serverlorawan2:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8081:8080
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-serverlorawan2
    networks:
      lorawan2:
          aliases:
             - chirpstack-application-server

  chirpstack-gateway-bridgelorawan2:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1701:1700/udp
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquittolorawan2
    networks:
      lorawan2:
         ipv4_address: 10.100.130.10

  postgresqllorawan2:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ../../samples/chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./volumes/postgresqldatalorawan2:/var/lib/postgresql/data
    networks:
      lorawan2:
          aliases:
             - postgresql

  redislorawan2:
    image: redis:5-alpine
    volumes:
      - ./volumes/redisdatalorawan2:/data
    networks:
      lorawan2:
          aliases:
             - redis

  mosquittolorawan2:
    image: eclipse-mosquitto:2
    ports:
      - 1884:1883
    volumes:
      - ../../samples/chirpstack/configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
     lorawan2:
          aliases:
             - mosquitto

volumes:
  postgresqldatalorawan2:
  redisdatalorawan2:

networks:
  lorawan2:
    ipam:
      driver: default
      config:
        - subnet: 10.100.130.0/24
