version: "3"

services:
  chirpstack-network-serverlorawan1:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresqllorawan1
      - mosquittolorawan1
    networks:
      lorawan1:
        aliases:
           - chirpstack-network-server

  chirpstack-application-serverlorawan1:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-serverlorawan1
    networks:
      lorawan1:
          aliases:
             - chirpstack-application-server

  chirpstack-gateway-bridgelorawan1:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ../../samples/chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquittolorawan1
    networks:
      lorawan1:
         ipv4_address: 10.100.120.10

  postgresqllorawan1:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ../../samples/chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./volumes/postgresqldatalorawan1:/var/lib/postgresql/data
    networks:
      lorawan1:
          aliases:
             - postgresql

  redislorawan1:
    image: redis:5-alpine
    volumes:
      - ./volumes/redisdatalorawan1:/data
    networks:
      lorawan1:
          aliases:
             - redis

  mosquittolorawan1:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ../../samples/chirpstack/configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
     lorawan1:
          aliases:
             - mosquitto

volumes:
  postgresqldatalorawan1:
  redisdatalorawan1:

networks:
  lorawan1:
    ipam:
      driver: default
      config:
        - subnet: 10.100.120.0/24
